### PR TITLE
Added analytic event for vaulted card

### PR DESCRIPTION
**Pull request by scannillo**
- We previously collected analytic events for tokenization on new card creation only. This PR adds an analytic event for choosing an already vaulted card.

Events:
- Start event "vaulted-card.appear": when all vaulted cards are shown
- Success event "vaulted-card.select": when a vaulted card is chosen

Will squash before merge.

### CODE REVIEW

**Comment by scannillo** [comment]
> Does iOS Drop-in not have unit tests around analytics?
Currently, there are none.

**Comment by scannillo** [comment]
> Does iOS Drop-in not have unit tests around analytics?

Currently, there are none.

**Comment by billwerges** [comment]
Do we have this event in the Android and Web drop-in projects already?

**Comment by scannillo** [comment]
> Do we have this event in the Android and Web drop-in projects already?

Here is a [PR for Android](https://github.com/braintree/braintree-android-drop-in/pull/130). This task is in progress for Web.

**Comment by hollabaq86** [comment]
@demerino That's phase 2 😄.

**Pull request merged**
